# Generated by Django 3.0.8 on 2020-10-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='canadaNational',
        ),
        migrations.AddField(
            model_name='cv',
            name='canadanational',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='confirmemail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='confirmpassword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
