# Generated by Django 3.0.8 on 2020-10-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201022_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
