# Generated by Django 3.0.8 on 2020-10-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201022_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
