# Generated by Django 3.0.8 on 2020-10-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201022_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
